version: "3.9"
services:
  tf-gpu:
    container_name: tf-gpu-env
    image: tf-gpu-env:0.0.0-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
          - driver: "nvidia"
            device_ids: ["0"]
            capabilities: [gpu]
    ports:
      - 8888:8888
    volumes:
      - ./data/:/data
      - ./logs:/usr/src/tf-env/logs
    networks:
      - internal-net
networks:
  internal-net: