version: "3.9"
services:
  tf-gpu:
    container_name: tf-gpu-env
    image: tf-gpu-env:0.0.0-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    env_file: .env
    volumes:
      - ./data/:/usr/src/tf-env/data
      - ./logs:/usr/src/tf-env/logs
    networks:
      - internal-net
networks:
  internal-net: